# See j2objc-gradle's .travis.yml for explanations.

language: objective-c
os: osx
osx_image: xcode7

# Add a TEST_DIR=[directory] row for each library (or group of libraries) to test
# Each will be run as an independent, hermetic test (in parallel when resources permit)
# on Traivs.
env:
  - TEST_DIR=com.google.code.gson-gson
  - TEST_DIR=org.joda-joda-convert
  - TEST_DIR=joda-time-joda-time
  - TEST_DIR=org.joda-joda-primitives
  - TEST_DIR=org.apache.commons-commons-lang3

# Uncomment to add a library that should fail to build, along with documentation on why.
# matrix:
#   allow_failures:
#     # Blocked on (github issue url)
#     - env: TEST_DIR=com.example-library
      - env: TEST_DIR=com.fasterxml.jackson.core

branches:
  only:
    - master
    - /^release.*$/
    - /^v[0-9].*$/

sudo: false


before_install:
  - export TERM=dumb
  - env
  - ./j2objc-gradle/install-osx-jdk7.sh

install:
  - export TERM=dumb
  - env
  - xcrun clang -v
  - /usr/libexec/java_home -v 1.7 -F -V
  - java -Xmx32m -version && javac -J-Xmx32m -version
  - pushd j2objc-gradle
  - ./gradlew wrapper
  - ./gradlew dependencies
  # In this repo, building of the j2objc-gradle plugin is just preperation.
  - ./gradlew build
  - popd
  - pushd libraryBuilds
  # Downloads and configures j2objc distribution.
  - ./prep.sh

# Note the install prep leaves us in the libraryBuilds directory.
script:
  - ./run-test.sh $TEST_DIR
